name: Update checklists

on:
  workflow_dispatch:
  schedule:
    # Every week
    - cron: '0 0 * * 0'
    # Every 24 hours
    # - cron: '0 */24 * * *'

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:

  update:
    runs-on: macos-latest
    steps:
      - name: Update Homebrew
        run: brew update-reset

      - name: Check out repository
        uses: actions/checkout@main

      - name: Update checklists
        run: |
          cd $GITHUB_WORKSPACE
          ./update-checklists.sh

      - name: Commit checklists
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update checklists
          commit_user_name: SeekerTestBot
          commit_user_email: 68891797+SeekerTestBot@users.noreply.github.com
          commit_author: SeekerTestBot <68891797+SeekerTestBot@users.noreply.github.com>
