name: Update checklists

on:
  workflow_dispatch:
  schedule:
    # Every 12 hours
    - cron: '0 */12 * * *'

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:

  update:
    if: ${{ !github.event.inputs.skip_core }}
    runs-on: macos-latest
    steps:
      - name: Update Homebrew
        run: brew update-reset

      - name: Check out repository
        uses: actions/checkout@main

      - name: Update checklists
        run: |
          cd $GITHUB_WORKSPACE
          ./update-checklists.sh

      - name: Commit checklists
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update checklists
